### ISSUE TITLE
freezing backbone part

### ISSUE THREAD

**Issue by XhqGlorry11** [chensnathan/YOLOF#11]
@chensnathan Hello, nice work! In the code, in addition to batchnorm layers in backbone, I noticed that stem conv and res2 block of res50 are also freezed during training. Is that a principle design or u just find it will achieve better training process if these additional layers are freezed?

**Comment by chensnathan** [comment]
It is a conventional setting for detection. You can check [here](https://github.com/facebookresearch/detectron2/blob/3ef82d22e58e947285dccb5c313e620e93bf0024/detectron2/config/defaults.py#L128) for more details.
