### ISSUE TITLE
uniform matcher可以给一个更详细的注释吗

### ISSUE THREAD

**Issue by muyihao** [chensnathan/YOLOF#13]
uniform matcher的有些难理解，希望有更多注释

**Comment by chensnathan** [comment]
Ok, I will add detailed comments in the next few days.

**Comment by chensnathan** [comment]
Please check [this commit](https://github.com/chensnathan/YOLOF/commit/a44b7af0efa9b89d3e91db70bc9a39e49d5d0144) for more comments about the matching.
