### ISSUE TITLE
a map

### ISSUE THREAD

**Issue by wanghangege** [chensnathan/YOLOF#16]

**Comment by wanghangege** [comment]
I used the base training file (Base-YOLOF.yaml) and obtained a training accuracy of about 14%. Using the best training file (YOLOF_CSP_D_53_DC5_9x_stage2_3x.yaml) in the table, I got about 38% mAP. I used two titanV graphics cards, so adjusted the batch, not sure if that affected it.

**Comment by chensnathan** [comment]
The settings are made for 8 GPUs, when you have only 2 GPUs, you should adjust the learning rate, the iterations, the warmup iterations, and the warmup learning rate factor according to [the linear scaling rule](https://github.com/chensnathan/YOLOF/issues/3#issuecomment-805452062).

**Comment by wanghangege** [comment]
> The settings are made for 8 GPUs, when you have only 2 GPUs, you should adjust the learning rate, the iterations, the warmup iterations, and the warmup learning rate factor according to [the linear scaling rule](https://github.com/chensnathan/YOLOF/issues/3#issuecomment-805452062).

thanks, I forgot it.
