### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by woshichunge12** [chensnathan/YOLOF#21]
Hello, first of all thank you and your team for your accomplishments.
Is the datasets folder created by myself when I created the dataset, and is it that I can only use data in COCO format?

**Comment by x-x110** [comment]
you can see https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html to learn how to register dataset

**Comment by woshichunge12** [comment]
> you can see https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html to learn how to register dataset

thank you,If I need to train on my own data set, do I need to change anything?

**Comment by x-x110** [comment]
https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html introduce how to use own data set
