### ISSUE TITLE
A problem about the code at train_net.py ?

### ISSUE THREAD

**Issue by randomNNN** [chensnathan/YOLOF#23]
Dear author,I have had a problem when I saw the code: 
optimizer = torch.optim.SGD(            params, cfg.SOLVER.BASE_LR, momentum=cfg.SOLVER.MOMENTUM        )
where you aren't define the cfg.SOLVER.MOMENTUM in the configs.Appreciate!

**Comment by chensnathan** [comment]
Hi, we adopt many default settings in Detectron2. And we only give the modification configs in this repo. Detailed setting for `SOLVER.MOMENTUM` can be found [here](https://github.com/facebookresearch/detectron2/blob/master/detectron2/config/defaults.py#L514).

**Comment by randomNNN** [comment]
Thank for your reply.When I first saw your paper,the YOLOF's network architecture really surprised me,the siso encoder and uniform matcher are brilliant.At the same time， I have an another problem,if I wanna instead the backbone  of mobilenetv3，and use the CA attention in the backbone.Can the OD model work well？Appreciate！------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月17日(星期四) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chensnathan/YOLOF] A problem about the code at train_net.py ? (#23)

**Comment by chensnathan** [comment]
Sorry for the late reply. 

YOLOF can definitely work well when you change a new backbone. You can try it with mobilenetv3.

**Comment by randomNNN** [comment]
Thanks for your reply.I will try to instead the backbone of lightwight model.And I have a presumptuous request.Can you give me a weChat、QQ&nbsp; or mailbox to communicate more detail.It's ok to refuse if this would bother you.Appreciate!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qiang ***@***.***&gt;; 
发送时间: 2021年6月20日(星期天) 晚上7:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chensnathan/YOLOF] A problem about the code at train_net.py ? (#23)





 
Sorry for the late reply.
 
YOLOF can definitely work well when you change a new backbone. You can try it with mobilenetv3.

**Comment by chensnathan** [comment]
qiang.chen@nlpr.ia.ac.cn

If you have any questions, feel free to drop me an email.

**Comment by randomNNN** [comment]
Thanks!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qiang ***@***.***&gt;; 
发送时间: 2021年6月21日(星期一) 下午5:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chensnathan/YOLOF] A problem about the code at train_net.py ? (#23)





 
***@***.***
 
If you have any questions, feel free to drop me an email.
