### ISSUE TITLE
AssertionError: bad box: x1 larger than x2

### ISSUE THREAD

**Issue by life97** [chensnathan/YOLOF#24]
Hello, dear author! When I train YOLOF with my own dataset, an error occurs. The error is as follows: File "G:\Anaconda3\envs\xyy_detectron2\lib\site-packages\fvcore\nn\giou_loss.py", line 32, in giou_loss
     assert (x2 >= x1).all(), "bad box: x1 larger than x2"
AssertionError: bad box: x1 larger than x2
Always run a few epochs will report such an error, try to comment out the assertion, the loss will be nan. How to solve this problem? I would be very grateful if you could help me.

![QQ图片20210620164626](https://user-images.githubusercontent.com/56705432/122667759-1383fe00-d1e7-11eb-8e5f-e339a8c280dc.png)

**Comment by chensnathan** [comment]
Hi, you can post your full training log file here. I will try to help.

**Comment by life97** [comment]
Thank you very much for replying to me. This is my latest training log file.
[log.txt](https://github.com/chensnathan/YOLOF/files/6682237/log.txt)

**Comment by chensnathan** [comment]
It seems that you modify the config according to your experimental environment. If the batch size is smaller than the original setting, you may need to adjust the learning rate, the warm up iterations, the iteration steps. You can find an example in [this response](https://github.com/chensnathan/YOLOF/issues/19#issuecomment-846513566).

**Comment by life97** [comment]
Thank you very much for your patient reply, I will try again according to your opinion.

**Comment by life97** [comment]
Thank you very much for your suggestion, I have run through the program.
