### ISSUE TITLE
yolof_R_50_C5_1x Log

### ISSUE THREAD

**Issue by hhaAndroid** [chensnathan/YOLOF#6]
Hi, Can you provide the distributed training log corresponding to the `yolof_R_50_C5_1x.yaml` configuration

**Comment by chensnathan** [comment]
Check here. [yolof_r50_c5_1x.log](https://github.com/chensnathan/YOLOF/files/6226544/yolof_r50_c5_1x.log)

**Comment by hhaAndroid** [comment]
Thank you!

**Comment by chensnathan** [comment]
BTW, when we reimplement the model, we observe some variance (about 0.2~0.3 AP lower than the performance reported in the paper).

**Comment by hhaAndroid** [comment]
> BTW, when we reimplement the model, we observe some variance (about 0.2~0.3 AP lower than the performance reported in the paper).

OK
