### ISSUE TITLE
performance 

### ISSUE THREAD

**Issue by hhaAndroid** [chensnathan/YOLOF#7]
Thank you. I want to know how the performance of this depository is trained ？Is it exactly the same as in the table? If not, can you post the specific performance?

**Comment by chensnathan** [comment]
Yes. The models provided in the README are trained by this codebase.

**Comment by chensnathan** [comment]
Have you tried to train YOLOF with this codebase on your own?

**Comment by hhaAndroid** [comment]
> Have you tried to train YOLOF with this codebase on your own?

Yes

**Comment by chensnathan** [comment]
Could you achieve comparable results?

**Comment by hhaAndroid** [comment]
> Could you achieve comparable results?

Please wait

**Comment by hhaAndroid** [comment]
Yes, I ran three times, 37.5/37.6/37.7

**Comment by wanghangege** [comment]
> Yes, I ran three times, 37.5/37.6/37.7

Hi, may I ask which yaml profile you are running, I am using the "yolof_CSP_D_53_DC5_9x_stage2_3x.yaml" and getting about 38% mAP.
